Games_fbv/urls.py
from django.urls import path

from Games_fbv import views

app_name = 'Games_fbv'


#Casamento de URLs
urlpatterns = [
 
  path('', views.Game_list, name='Game_list'),
  path('new', views.Game_create, name='Game_new'),
  path('edit/<int:pk>', views.Game_update, name='Game_edit'),
  path('delete/<int:pk>', views.Game_delete, name='Game_delete'),
]

apps/urls.py
from django.urls import include, path
from django.contrib import admin

from theme import views

#Casamento de URLs
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Games_fbv.urls', namespace='Games_fbv')),
]

Games_fbv/models.py
from django.db import models
from django.urls import reverse

#Model para o Form Game
class Game(models.Model):
    name = models.CharField(max_length=200)
    contato = models.CharField(max_length=50)
    originalum = models.FloatField(default=0)
    originaldois = models.FloatField(default=0)
    fantasma = models.FloatField(default=0)
    senha = models.CharField(max_length=200)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Games_fbv:Game_edit', kwargs={'pk': self.pk})
    
    
    

theme/models.py
from django.db import models

Games_fbv/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django import forms
from Games_fbv.models import Game

#Form de cadastro de jogo
class GameForm(ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'contato','originalum','originaldois','fantasma','senha']  
        labels = {
            "originalum": "Original Um",
            "originaldois": "Original Dois",
            "fantasma": "Fantasma",
        }
    # Validação
    def is_valid(self):
        
        valid = super(GameForm, self).is_valid()
        
        if not valid:
            return valid
        #Valida se contato é um numero valido (não possui letras)
        contato = self.cleaned_data['contato']
        try: 
            int(contato)
            if(self.cleaned_data['originalum'] == 0 and self.cleaned_data['originaldois'] == 0 and self.cleaned_data['fantasma'] == 0):
                self.add_error('originalum','Ao menos um dos valores deve ser diferente de zero')
                return False
            return True
        except ValueError:
            self.add_error('contato', 'Digite apenas números')
            return False
            
        
    
 #Form de edição de jogo
class GameFormEdit(ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'contato','originalum','originaldois','fantasma','senha']
        labels = {
            "originalum": "Original Um",
            "originaldois": "Original Dois",
            "fantasma": "Fantasma",
        }
    #Validação
    def is_valid(self,aux):
        
        valid = super(GameFormEdit, self).is_valid()
        
        if not valid:
            return valid
        #Validação da senha
        if (self.cleaned_data['senha'] != aux):
            self.add_error('senha', 'Senha incorreta')
            return False
            
        contato = self.cleaned_data['contato']
        try: 
            int(contato)
            if(self.cleaned_data['originalum'] == 0 and self.cleaned_data['originaldois'] == 0 and self.cleaned_data['fantasma'] == 0):
                self.add_error('originalum','Ao menos um dos valores deve ser diferente de zero')
                return False
            return True
        except ValueError:
            self.add_error('contato', 'Digite apenas números')
            return False
        
        return True
  
#Form de deletar jogo 
class GameFormDelete(ModelForm):
    class Meta:
        model = Game
        fields = ['senha']
        
    def is_valid(self,aux):
        
        valid = super(GameFormDelete, self).is_valid()
        
        if not valid:
            return valid
        #Validação da senha
        if (self.cleaned_data['senha'] != aux):
            self.add_error('senha', 'Senha incorreta')
            return False    
        return True

def Game_list(request, template_name='Games_fbv/Game_list.html'):
    game = Game.objects.all()
    data = {}
    data['object_list'] = game
    return render(request, template_name, data)

def Game_create(request, template_name='Games_fbv/Game_form.html'):
    game = Game()
    game.contato = "Digite telefone com ID do país e DDD"
    form = GameForm(request.POST or None, instance=game)
    if form.is_valid():
        form.save()
        return redirect('Games_fbv:Game_list')
    
    return render(request, template_name, {'form':form})

def Game_update(request, pk, template_name='Games_fbv/Game_form.html'):
    game = get_object_or_404(Game, pk=pk)
    aux = game.senha
    game.senha = "Digite a senha correta"
    form = GameFormEdit(request.POST or None, instance=game)
    if form.is_valid(aux):
        form.save()
        return redirect('Games_fbv:Game_list')
    else:
        
        return render(request, template_name, {'form':form})

def Game_delete(request, pk, template_name='Games_fbv/Game_confirm_delete.html'):
    game = get_object_or_404(Game, pk=pk) 
    aux = game.senha
    game.senha = "Digite a senha correta"
    form = GameFormDelete(request.POST or None, instance=game)    
    if form.is_valid(aux):
        game.delete()
        return redirect('Games_fbv:Game_list')
    return render(request, template_name, {'form':form})

apps/views.py
from django.shortcuts import render

theme/views.py
from django.shortcuts import render

def home(request):
    return render(request, "home.html")

Games_fbv/templates/Games_fbv/Game_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block content1 %}

<div class="col-12 form-popup align-middle " id="myFormCadastroJogo" style="display:block"> 
    <form class="form-container text-center form-container-cadastro-jogo" method="post">{% csrf_token %}
        <h1>Deletar Jogo</h1>	
            {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Deletar</button>
        <button type="button" class="btn  btn-form cancel" onclick="paginaInicial()">Voltar</button>
    </form>
</div>

{% endblock %}

Games_fbv/templates/Games_fbv/Game_form.html
{% extends "base.html" %}
{% load static %}
{% block content1 %}
<div class="col-12 form-popup align-middle " id="myFormCadastroJogo" style="display:block"> 
    <form class="form-container text-center form-container-cadastro-jogo" method="post">{% csrf_token %}
        <h1>Formulario de Jogo</h1>	
            {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submeter</button>
        <button type="button" class="btn  btn-form cancel" onclick="paginaInicial()">Voltar</button>
    </form>
</div>
{% endblock %}

Games_fbv/templates/Games_fbv/Game_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<div class="container-fluid">
	
			{% for Game in object_list %}
			<div class="row game-row">
			
			<div class="col-12 col-sm-6 col-md-6 col-xl-3 game-item-colorido game-item-colorido-low-resolution d-flex align-items-center" style="text-transform:uppercase;">
			{{ Game.name }}
			</div>
			<div class="col-4 col-sm-2 col-md-2 col-xl-2 text-center">
			<small> OR1 </small> <br>
			{%if Game.originalum == 0 %}
				--
			{% else %}
				R${{Game.originalum}}
			{% endif %}
			</div>
			
			<div class="col-4 col-sm-2 col-md-2 col-xl-2 text-center">
			<small> OR2 </small> <br>
			{%if Game.originaldois == 0 %}
				--
			{% else %}
				R${{Game.originaldois}}
			{% endif %}
			</div>
			
			<div class="col-4 col-sm-2 col-md-2 col-xl-2 text-center">
			<small> FTN </small> <br>
			{%if Game.fantasma == 0 %}
				--
			{% else %}
				R${{Game.fantasma}}
			{% endif %}
			</div>
			<div class="col-6 col-sm-6 col-md-6 col-xl-2 align-items-center d-flex text-center" style="
    padding: 0px;
    
">
			<a class="botoes-lista " href="{% url 'Games_fbv:Game_delete' Game.id %}">
			<button  class="btn botao-linha primeira-coluna" type="button" style="
    border-right: 2px;
    
    border-style: dashed;"> Excluir </button ></a>
	
	
	<a  class="botoes-lista"  href="{% url 'Games_fbv:Game_edit' Game.id %}" style="width:100%;">
			<button  class="btn botao-linha" type="button" style="
    border-right: 2px;
    border-radius: 0px;
    border-style: dashed;"> Editar </button ></a>
			</div>

			<div class="col-6 col-sm-6 col-md-6 col-xl-1 ultima-coluna" style="
    left: -1px;
">
			
	<a  class="botoes-lista"  href="https://api.whatsapp.com/send?phone={{Game.contato}}" style="width:100%;">
			
			<button  class="btn botao-linha" type="button" style="
    left: 0px;
    position: relative;
    left: 1px;"> Contato </button > </a>
			</div>
			
			</div>
			<!-- <li>{{ Game.name }}  ({{ Game.contato }} Pages) -->
			<!-- <a href="{% url 'Games_fbv:Game_edit' Game.id %}">edit</a> -->
			<!-- <a href="{% url 'Games_fbv:Game_delete' Game.id %}">delete</a> -->
			<!-- </li> -->
			{% endfor %}
		</ul>
	</div>



{% endblock %}

theme/templates/home.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'books_cbv:book_list' %}">Class Based Views</a><br>
<a href="{% url 'books_fbv:book_list' %}">Function Based Views</a><br>    
<a href="{% url 'books_fbv_user:book_list' %}">Function Based Views with User Access</a><br>    

{% endblock %}